export const DATA_FETCHING = "DATA_FETCHING";
export const DATA_FETCHED = "DATA_FETCHED";
export const DATA_ERROR = "DATA_ERROR";

export const SET_ACCESS_TOKENS = "SET_ACCESS_TOKENS";

export const SEARCH_ALBUMS = "SEARCH_ALBUMS";

export const ADD_ALBUM_TO_LIST = "ADD_ALBUM_TO_LIST";
export const DELETE_ALBUM_FROM_LIST = "DELETE_ALBUM_FROM_LIST";

export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const PLAY_CURRENT_TRACK = "PLAY_CURRENT_TRACK";
export const STOP_PLAYING_TRACK = "STOP_PLAYING_TRACK";
export const PAUSE_PLAYING_TRACK = "PAUSE_PLAYING_TRACK";
export const NEXT_PREV_TRACK = "NEXT_PREV_TRACK";

export const SHOW_ALBUM_DETAILS = "SHOW_ALBUM_DETAILS";
export const HIDE_ALBUM_DETAILS = "HIDE_ALBUM_DETAILS";
export const SET_ALBUM_DETAILS = "SET_ALBUM_DETAILS";

export const SHOW_SEARCH_RESULTS = "SHOW_SEARCH_RESULTS";
export const HIDE_SEARCH_RESULTS = "HIDE_SEARCH_RESULTS";
