export const SET_ACCESS_TOKENS = "SET_ACCESS_TOKENS";
export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const ADD_ALBUM_TO_LIST = "ADD_ALBUM_TO_LIST";
export const DELETE_ALBUM_FROM_LIST = "DELETE_ALBUM_FROM_LIST";
